import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { authApi } from "../api";
import StatusMessage from "../components/StatusMessage";

export default function Register() {
  const navigate = useNavigate(); const [form, setForm] = useState({ full_name: "", email: "", password: "", confirmPassword: "" }); const [status, setStatus] = useState({ loading: false, error: "", success: "" });
  function validate() { if (!form.full_name.trim()) return "Name is required."; if (form.password.length < 6) return "Password must be at least 6 characters."; if (form.password !== form.confirmPassword) return "Passwords do not match."; return ""; }
  async function submit(event) { event.preventDefault(); const validationError = validate(); if (validationError) return setStatus({ loading: false, error: validationError, success: "" }); setStatus({ loading: true, error: "", success: "" }); try { const result = await authApi.register({ full_name: form.full_name, email: form.email, password: form.password }); setStatus({ loading: false, error: "", success: result.message }); setTimeout(() => navigate("/login"), 900); } catch (error) { setStatus({ loading: false, error: error.message, success: "" }); } }
  return <section className="auth-page"><div className="auth-copy"><span className="eyebrow">Start learning</span><h1>Make room for <i>better work.</i></h1><p>Create your learner account and find a course with a clear next step.</p></div><form className="form-card" onSubmit={submit}><h2>Create account</h2><p className="muted">Your learning path begins with the basics.</p>{status.error && <StatusMessage>{status.error}</StatusMessage>}{status.success && <StatusMessage type="success">{status.success}</StatusMessage>}<label>Full name<input value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></label><label>Password<input type="password" minLength="6" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /></label><label>Confirm password<input type="password" value={form.confirmPassword} onChange={(event) => setForm({ ...form, confirmPassword: event.target.value })} required /></label><button className="button full" disabled={status.loading}>{status.loading ? "Creating account..." : "Create account"}</button><p className="form-foot">Already registered? <Link to="/login">Log in</Link></p></form></section>;
}
